'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createContext, useEffect, useState } from "react";



  // Import the functions you need from the SDKs you need
  import { initializeApp } from "firebase/app";
  import firestore, { Firestore, getFirestore } from "firebase/firestore";
  // TODO: Add SDKs for Firebase products that you want to use

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration


// export const StreamingContext = createContext<{
//   pc: RTCPeerConnection | undefined,
//   firestore: firestore.Firestore
// }>(null!);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [pc, setPC] = useState<RTCPeerConnection>();

  // useEffect(() => {
  //   console.log("setting pc");
  //   setPC(new RTCPeerConnection(servers));
  // }, [])

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
